"""Hook shim generation utilities.

Two shim variants:

``write_decision_shim`` — for *decision-path* plugins (agentmemory, agentwiki).
    Fills the existing ``template.sh`` (synchronous Python invocation, exits 2
    for explicit block, always exits 0 on any other error).

``write_capture_shim`` — for *capture-path* plugins (agentaudit).
    Writes a 3-tier shim: daemon socket fast-path → atomic spool file →
    background drain subprocess.  Always exits 0 so Claude Code is never
    blocked.  The spool file is atomic (POSIX rename) so events cannot be
    lost after it lands.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path
from string import Template

# ---------------------------------------------------------------------------
# Decision-path shim (fills the SDK's existing template.sh)
# ---------------------------------------------------------------------------

_DECISION_TEMPLATE_PATH = Path(__file__).parent.parent / "hooks" / "template.sh"

_CAPTURE_TEMPLATE = """\
#!/usr/bin/env bash
# Native Agents capture-path hook — generated by nativeagents-sdk.
# DO NOT EDIT — regenerate with sdk.install.write_capture_shim().
#
# Three-tier capture (fastest first):
#   Tier 0  daemon socket (<5 ms, no Python startup cost)
#   Tier 1  atomic spool file (<15 ms synchronous, durable after rename)
#   Tier 2  background drain subprocess (async, may lose if OS kills it)
#
# Always exits 0 — never interferes with Claude Code.

set -u

PLUGIN_NAME="$plugin_name"
PYTHON="$python_executable"
SPOOL_DIR="$spool_dir"
DAEMON_SOCK="$daemon_sock"
DRAIN_MODULE="$drain_module"

export NATIVEAGENTS_PLUGIN_NAME="$$PLUGIN_NAME"
export PYTHONUNBUFFERED=1

# ── Read stdin ────────────────────────────────────────────────────────────
input=$$(cat)

event_type="$${HOOK_EVENT_NAME:-}"
if [ -z "$$event_type" ]; then
    event_type=$$(printf '%s' "$$input" | "$$PYTHON" -c \\
        "import sys,json; print(json.load(sys.stdin).get('hook_event_name','unknown'))" \\
        2>/dev/null || echo "unknown")
fi

# ── Tier 0: daemon socket ────────────────────────────────────────────────
if [ -S "$$DAEMON_SOCK" ]; then
    if "$$PYTHON" -c "
import socket, sys
data = (sys.argv[1] + '\\n' + sys.argv[2] + '\\n\\n').encode('utf-8')
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.settimeout(2)
try:
    s.connect(sys.argv[3]); s.sendall(data); s.shutdown(socket.SHUT_WR)
    ack = s.recv(4); s.close()
    sys.exit(0 if ack.strip() == b'ok' else 1)
except Exception:
    sys.exit(1)
" "$$event_type" "$$input" "$$DAEMON_SOCK" 2>/dev/null; then
        exit 0
    fi
fi

# ── Tier 1: atomic spool file ────────────────────────────────────────────
mkdir -p "$$SPOOL_DIR"
ts=$$(date +%s)
rand=$$(openssl rand -hex 8 2>/dev/null \\
    || "$$PYTHON" -c "import secrets; print(secrets.token_hex(8))" 2>/dev/null \\
    || echo "$$$$${PPID}")
spool="$$SPOOL_DIR/$${ts}-$$$$-$${rand}.json"
tmp="$${spool}.tmp"
printf '%s\\n%s' "$$event_type" "$$input" > "$$tmp"
mv "$$tmp" "$$spool"

# ── Tier 2: kick drain (async) ───────────────────────────────────────────
"$$PYTHON" -m "$$DRAIN_MODULE" 2>/dev/null &

exit 0
"""


def write_decision_shim(
    plugin_name: str,
    python_executable: str | Path,
    module: str,
    dest: Path,
) -> Path:
    """Write a decision-path hook shim from the SDK template.

    The generated script invokes ``python -m <module>`` synchronously,
    exits 2 on explicit block, and exits 0 on any other outcome.

    Args:
        plugin_name: Plugin name embedded in the shim for logging.
        python_executable: Absolute path to the Python interpreter.
        module: Python module to invoke (e.g. ``"agentmemory.hook"``).
        dest: Where to write the ``.sh`` file.

    Returns:
        ``dest`` with execute permissions set (0o755).

    Raises:
        OSError: If the template cannot be read or dest cannot be written.
    """
    template_text = _DECISION_TEMPLATE_PATH.read_text(encoding="utf-8")
    content = (
        template_text.replace("{{PLUGIN_NAME}}", plugin_name)
        .replace("{{PYTHON_EXECUTABLE}}", str(python_executable))
        .replace("{{PYTHON_MODULE}}", module)
    )
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    dest.chmod(0o755)
    return dest


def write_capture_shim(
    plugin_name: str,
    python_executable: str | Path,
    spool_dir: str | Path,
    drain_module: str,
    dest: Path,
    daemon_sock: str | Path | None = None,
) -> Path:
    """Write a capture-path hook shim (3-tier: socket → spool → drain).

    The generated script NEVER blocks Claude Code — it always exits 0.
    The spool file is written atomically (POSIX rename) so events are
    durable even if the drain subprocess is killed.

    Args:
        plugin_name: Plugin name embedded in the shim for env/logging.
        python_executable: Absolute path to the Python interpreter.
        spool_dir: Directory where spool files are written.
        drain_module: Python module that drains spool files into storage
            (e.g. ``"agentaudit.drain"``).  Invoked as ``python -m <module>``.
        dest: Where to write the ``.sh`` file.
        daemon_sock: Optional UNIX socket path for the Tier-0 fast path.
            Tier-0 is skipped if ``None`` or the socket does not exist at
            runtime.

    Returns:
        ``dest`` with execute permissions set (0o755).

    Raises:
        OSError: If dest cannot be written.
    """
    sock_path = str(daemon_sock) if daemon_sock is not None else ""
    content = Template(_CAPTURE_TEMPLATE).safe_substitute(
        plugin_name=plugin_name,
        python_executable=str(python_executable),
        spool_dir=str(spool_dir),
        daemon_sock=sock_path,
        drain_module=drain_module,
    )
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    dest.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
    return dest


def shim_is_executable(path: Path) -> bool:
    """Return True if ``path`` exists and has the executable bit set for owner."""
    try:
        return bool(os.stat(path).st_mode & stat.S_IXUSR)
    except FileNotFoundError:
        return False
